#!/usr/bin/env python3
"""Generate additive AOS V200 redirects block for .htaccess."""
from __future__ import annotations

from collections import Counter
from _lib import (
    BLOCK_END,
    BLOCK_START,
    DECISIONS_PATH,
    HERITAGE_PAGE_ID,
    HERITAGE_TARGET,
    HTACCESS_BLOCK_PATH,
    iso_utc_now,
    load_decisions,
    quote_slug,
    quote_url_path,
)


def build_rewrite_line(old_slug: str, target_url: str) -> str:
    old_encoded = quote_slug(old_slug)
    target_encoded = quote_url_path(target_url)
    return f"RewriteRule ^{old_encoded}/?$ {target_encoded} [R=301,L]"


def main() -> int:
    data = load_decisions()
    rows = data.get("decisions", [])

    redirects = [r for r in rows if r.get("decision") == "redirect"]
    drops = [r for r in rows if r.get("decision") == "drop"]

    # Put longer patterns first for deterministic, safe matching.
    redirects_sorted = sorted(redirects, key=lambda r: len(r.get("slug", "")), reverse=True)
    drops_sorted = sorted(drops, key=lambda r: len(r.get("slug", "")), reverse=True)

    redirect_lines: list[str] = []
    for row in redirects_sorted:
        slug = row.get("slug", "").strip()
        new_url = row.get("new_url")
        if not slug or not new_url:
            raise RuntimeError(f"Redirect row missing slug/new_url: id={row.get('id')}")
        redirect_lines.append(build_rewrite_line(slug, new_url))

    drop_lines: list[str] = []
    for row in drops_sorted:
        slug = row.get("slug", "").strip()
        if not slug:
            raise RuntimeError(f"Drop row missing slug: id={row.get('id')}")
        drop_lines.append(f"RewriteRule ^{quote_slug(slug)}/?$ - [G,L]")

    # Legacy fallback for old WordPress query permalinks to heritage.
    heritage_rule = (
        f"RewriteCond %{{QUERY_STRING}} (^|&)page_id={HERITAGE_PAGE_ID}(&|$)\n"
        f"RewriteRule ^$ {quote_url_path(HERITAGE_TARGET)} [R=301,L]"
    )

    rewrite_rule_count = len(redirect_lines) + len(drop_lines) + 1

    lines: list[str] = [
        "# ============================================================",
        f"{BLOCK_START} — DO NOT EDIT BY HAND",
        "# Generated by scripts/redirects/generate_htaccess_block.py",
        f"# Source: {DECISIONS_PATH}",
        f"# Generated: {iso_utc_now()}",
        f"# Total: {len(redirect_lines)} redirects + {len(drop_lines)} 410 Gone + 1 heritage special",
        "# ============================================================",
        "<IfModule mod_rewrite.c>",
        "RewriteEngine On",
        "",
        "# --- 301 Redirects (URL-encoded Hebrew slugs) ---",
        *redirect_lines,
        "",
        "# --- Heritage special fallback (/ ?page_id=2516) ---",
        heritage_rule,
        "",
        "# --- 410 Gone (drops) ---",
        *drop_lines,
        "</IfModule>",
        BLOCK_END,
        "",
    ]

    HTACCESS_BLOCK_PATH.parent.mkdir(parents=True, exist_ok=True)
    HTACCESS_BLOCK_PATH.write_text("\n".join(lines), encoding="utf-8")

    counter = Counter(r.get("decision") for r in rows)
    print(f"[OK] Wrote: {HTACCESS_BLOCK_PATH}")
    print(
        "[INFO] Decisions: "
        f"redirect={counter.get('redirect', 0)} keep={counter.get('keep', 0)} drop={counter.get('drop', 0)}"
    )
    print(f"[INFO] RewriteRule lines: {rewrite_rule_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
